package:
  name: pythonutils
  version: 0.0.1

source:
  git_url: https://github.com/RSTZZZ/pythonutils.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - loguru

test:
  imports:
    - pythonutils

about:
  home: https://github.com/RSTZZZ/pythonutils
